name: sxt_seg
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiofiles=22.1.0=py311h06a4308_0
  - aiosqlite=0.18.0=py311h06a4308_0
  - anyio=3.5.0=py311h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atk-1.0=2.36.0=h516909a_2
  - attrs=22.1.0=py311h06a4308_0
  - aws-requests-auth=0.4.2=py_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h6a678d5_0
  - boto3=1.34.144=pyhd8ed1ab_0
  - botocore=1.34.144=pyge310_1234567_0
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py311h5eee18b_1002
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.15.1=py311h5eee18b_3
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py311h06a4308_0
  - cloudpickle=2.2.1=py311h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py311h06a4308_0
  - contourpy=1.0.5=py311hdb19cb5_0
  - cryptography=39.0.1=py311h9ce1e76_2
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py311h5eee18b_0
  - dask-core=2023.6.0=py311h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=py311h06a4308_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.1=h52c9d5c_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - fpdf=1.7.2=pyhd8ed1ab_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.10=h5eee18b_0
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.72.0=py311hbb6d50b_2
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h3cd0ef9_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=h08bb679_0
  - harfbuzz=4.3.0=hf52aaf7_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py311h06a4308_0
  - imagecodecs=2021.8.26=py311hb63acbb_2
  - imageio=2.31.1=py311h06a4308_0
  - importlib-metadata=6.0.0=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.19.2=py311h6410fe4_0
  - ipython=8.12.0=py311h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py311h06a4308_0
  - jedi=0.18.1=py311h06a4308_1
  - jinja2=3.1.2=py311h06a4308_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.2.0=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonlines=1.2.0=pyh9f0ad1d_2
  - jsonschema=4.17.3=py311h06a4308_0
  - jupyter=1.0.0=py311h06a4308_8
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.3.0=py311h06a4308_0
  - jupyter_events=0.6.3=py311h06a4308_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyter_server_terminals=0.4.4=py311h06a4308_1
  - jupyter_ydoc=0.2.4=py311h06a4308_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=3.0.5=py311h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libaec=1.0.4=he6710b0_1
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcurl=8.1.1=h251f7ec_1
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h6a678d5_3
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libnghttp2=1.52.0=h2d74bed_1
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libprotobuf=4.25.3=he621ea3_0
  - librsvg=2.54.4=h36cc946_2
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libtool=2.4.6=h9c3ff4c_1008
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzopfli=1.0.3=he6710b0_0
  - locket=1.0.0=py311h06a4308_0
  - lxml=4.9.1=py311h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib=3.7.1=py311h06a4308_1
  - matplotlib-base=3.7.1=py311ha02d727_1
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mistune=0.8.4=py311h5eee18b_1000
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.6=py311ha02d727_1
  - mkl_random=1.2.2=py311ha02d727_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py311h06a4308_0
  - mrc=0.3.1=pyhd8ed1ab_0
  - mrcfile=1.4.3=pyhd8ed1ab_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.5=py311h06a4308_0
  - nbclient=0.5.13=py311h06a4308_0
  - nbconvert=6.5.4=py311h06a4308_0
  - nbformat=5.7.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py311h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py311h06a4308_1
  - notebook=6.5.4=py311h06a4308_0
  - notebook-shim=0.2.2=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.25.0=py311h08b1b3b_0
  - numpy-base=1.25.0=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.1.5=py311h5eee18b_1
  - openssl=3.0.17=h5eee18b_0
  - packaging=23.0=py311h06a4308_0
  - pandas=2.1.4=py311ha02d727_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h05da053_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pathtools=0.1.2=py_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.1.2=py311h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=2.5.2=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.36=py311h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protobuf=4.25.3=py311h12ddb61_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py311h06a4308_0
  - pyparsing=3.0.9=py311h06a4308_0
  - pyqt=5.15.7=py311h6a678d5_0
  - pyqt5-sip=12.11.0=py311h6a678d5_0
  - pyrsistent=0.18.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-graphviz=0.20.1=pyh22cad53_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - pytorch=2.0.1=py3.11_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py311h06a4308_0
  - pywavelets=1.4.1=py311h5eee18b_0
  - pyyaml=6.0=py311h5eee18b_1
  - pyzmq=23.2.0=py311h6a678d5_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - quilt3=5.4.0=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - requests-futures=1.0.0=pyh9f0ad1d_2
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - s3transfer=0.10.2=pyhd8ed1ab_0
  - scikit-image=0.20.0=py311h6a678d5_0
  - scikit-learn=1.2.2=py311h6a678d5_1
  - scipy=1.10.1=py311h08b1b3b_1
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - sentry-sdk=2.10.0=pyhd8ed1ab_0
  - setproctitle=1.2.2=py311h5eee18b_0
  - setuptools=67.8.0=py311h06a4308_0
  - sip=6.6.2=py311h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py311h06a4308_1
  - soupsieve=2.4=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.2=py311hf4808d0_0
  - sympy=1.11.1=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.5.0=pyhd8ed1ab_0
  - tensorboardx=2.6.2.2=pyhd8ed1ab_0
  - terminado=0.17.1=py311h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py311h06a4308_0
  - torchaudio=2.0.2=py311_cu117
  - torchtriton=2.0.0=py311
  - torchvision=0.15.2=py311_cu117
  - tornado=6.2=py311h5eee18b_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=0.58.0=py311h06a4308_4
  - wheel=0.38.4=py311h06a4308_0
  - widgetsnbextension=4.0.5=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - y-py=0.5.9=py311h52d8a92_0
  - yaml=0.2.5=h7b6447c_0
  - ypy-websocket=0.8.2=py311h06a4308_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zipp=3.11.0=py311h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - app-model==0.4.0
      - astunparse==1.6.3
      - babel==2.17.0
      - build==1.3.0
      - cachetools==5.3.1
      - cachey==0.2.1
      - catboost==1.2.8
      - chardet==5.2.0
      - cupy-cuda12x==12.2.0
      - deprecated==1.2.14
      - docstring-parser==0.17.0
      - docutils==0.21.2
      - einops==0.8.1
      - fastrlock==0.8.2
      - flatbuffers==24.3.25
      - flexcache==0.3
      - flexparser==0.4
      - freetype-py==2.5.1
      - fsspec==2025.9.0
      - gast==0.6.0
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.0
      - h5py==3.11.0
      - heapdict==1.0.1
      - hf-xet==1.1.10
      - hsluv==5.0.4
      - huggingface-hub==0.35.3
      - humanize==4.12.3
      - imagesize==1.4.1
      - imbalanced-learn==0.12.3
      - imblearn==0.0
      - img2pdf==0.5.1
      - importlib-resources==6.5.2
      - in-n-out==0.2.1
      - ipython-pygments-lexers==1.1.1
      - keras==3.4.1
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightgbm==4.4.0
      - llvmlite==0.45.1
      - magicgui==0.10.1
      - markdown==3.5
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - namex==0.0.8
      - napari==0.6.5
      - napari-console==0.1.3
      - napari-plugin-engine==0.2.0
      - napari-svg==0.2.1
      - narwhals==2.6.0
      - nibabel==5.3.2
      - npe2==0.7.9
      - numba==0.62.1
      - numpydoc==1.9.0
      - nvidia-nccl-cu12==2.22.3
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - optree==0.12.1
      - patchify==0.2.3
      - pikepdf==8.11.2
      - pillow==10.2.0
      - pint==0.25
      - plotly==6.3.1
      - prettytable==3.9.0
      - psygnal==0.14.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyconify==0.2.1
      - pydantic==2.12.0
      - pydantic-compat==0.1.2
      - pydantic-core==2.41.1
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyproject-hooks==1.2.0
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - regex==2025.9.18
      - reportlab==4.0.8
      - requests==2.32.5
      - requests-oauthlib==1.3.1
      - rich==13.7.1
      - roman-numerals-py==3.1.0
      - rsa==4.9
      - safetensors==0.6.2
      - sentence-transformers==5.1.1
      - shap==0.48.0
      - shellingham==1.5.4
      - simpleitk==2.5.0
      - slicer==0.0.8
      - snowballstemmer==3.0.1
      - sphinx==8.2.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - superqt==0.7.6
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.17.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - tifffile==2025.10.4
      - tokenizers==0.22.1
      - tomli-w==1.2.0
      - torchio==0.20.8
      - torchsummary==1.5.1
      - torchview==0.2.6
      - transformers==4.57.0
      - typer==0.16.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - vispy==0.15.2
      - wandb==0.19.9
      - werkzeug==3.0.0
      - wrapt==1.17.2
      - xgboost==2.1.0

