name: sxt_seg
channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.11

  # core scientific stack
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image

  # visualization
  - matplotlib
  - seaborn

  # deep learning
  - pytorch
  - torchvision
  - torchaudio

  # notebooks & utilities
  - jupyter
  - jupyterlab
  - tqdm
  - pyyaml
  - rich

  # image / file IO
  - pillow
  - imageio
  - mrcfile
  - openpyxl

  # misc tools
  - networkx
  - python-graphviz

  - pip
  - pip:
      - albumentations
      - opencv-python
      - einops
      - patchify
      - quilt3
      - fpdf
